services:
  # A web service
  - type: web
    name: face-recognition-attendance
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python -c "from app import app, socketio; socketio.run(app, host='0.0.0.0', port=int('$PORT'), debug=False, allow_unsafe_werkzeug=True)"
    plan: standard # Use standard plan for more resources
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        sync: false # Will be manually set in Render dashboard
      - key: RENDER
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: WEB_CONCURRENCY
        value: "1"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 
